# -*- coding: utf-8 -*-
"""
Инструкция по настройке и тестированию Telegram-бота
"""

import os
from dotenv import load_dotenv

load_dotenv()

def main():
    print("=" * 70)
    print(" ПРОВЕРКА НАСТРОЕК TELEGRAM-БОТА")
    print("=" * 70)
    print()
    
    # Читаем переменные из .env
    token = os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
    chat_id = os.getenv("TELEGRAM_MANAGER_CHAT_ID", "").strip()
    
    print("[1] Проверка файла .env")
    print("-" * 70)
    
    if not token or token == "your_telegram_bot_token_here":
        print("[X] TELEGRAM_BOT_TOKEN не настроен!")
        print("    Текущее значение: не задано или placeholder")
        print()
        print("    Как исправить:")
        print("    1. Откройте @BotFather в Telegram")
        print("    2. Отправьте команду /newbot")
        print("    3. Следуйте инструкциям")
        print("    4. Скопируйте токен и вставьте в файл backend/.env")
        print()
        return
    else:
        print(f"[OK] TELEGRAM_BOT_TOKEN найден")
        print(f"     Значение (первые 15 символов): {token[:15]}...")
        print()
    
    if not chat_id or chat_id == "your_manager_chat_id_here":
        print("[X] TELEGRAM_MANAGER_CHAT_ID не настроен!")
        print("    Текущее значение: не задано или placeholder")
        print()
        print("    Как исправить:")
        print("    1. Откройте @userinfobot в Telegram")
        print("    2. Отправьте любое сообщение")
        print("    3. Скопируйте ваш Chat ID")
        print("    4. Вставьте в файл backend/.env")
        print()
        return
    else:
        print(f"[OK] TELEGRAM_MANAGER_CHAT_ID найден")
        print(f"     Значение: {chat_id}")
        print()
    
    print()
    print("[2] ВАЖНО: Начните диалог с ботом!")
    print("-" * 70)
    print()
    print("Чтобы бот мог отправлять вам сообщения, вы ДОЛЖНЫ:")
    print()
    print("1. Найти вашего бота в Telegram")
    print("   - Используйте поиск в Telegram")
    print("   - Или откройте ссылку: t.me/ИМЯ_ВАШЕГО_БОТА")
    print()
    print("2. Нажать кнопку 'START' в чате с ботом")
    print("   - Или отправить любое сообщение (например: /start или Привет)")
    print()
    print("3. После этого бот сможет отправлять вам уведомления")
    print()
    print()
    print("[3] Тестирование")
    print("-" * 70)
    print()
    print("После того как вы начали диалог с ботом, запустите:")
    print()
    print("    python test_telegram.py")
    print()
    print("Если всё настроено правильно, вы получите 4 сообщения в Telegram:")
    print("  - Тестовое сообщение")
    print("  - Уведомление о регистрации пользователя")
    print("  - Уведомление о Pro тарифе")
    print("  - Уведомление о Enterprise тарифе")
    print()
    print()
    print("[4] Возможные проблемы")
    print("-" * 70)
    print()
    print("Если сообщения не приходят:")
    print()
    print("a) Ошибка 404 (Not Found):")
    print("   - Вы не начали диалог с ботом → нажмите START в Telegram")
    print("   - Неверный Chat ID → проверьте в @userinfobot")
    print()
    print("b) Ошибка 401 (Unauthorized):")
    print("   - Неверный токен бота → проверьте токен в @BotFather")
    print()
    print("c) Timeout ошибка:")
    print("   - Проблемы с интернет-соединением")
    print("   - Telegram может быть заблокирован в вашей сети")
    print("   - Попробуйте использовать VPN")
    print()
    print()
    print("[5] Что делать дальше")
    print("-" * 70)
    print()
    print("После успешного тестирования:")
    print()
    print("1. Зарегистрируйте нового пользователя через frontend")
    print("   http://localhost:5173/register")
    print("   -> Должно прийти уведомление о регистрации")
    print()
    print("2. Выберите Pro тариф в настройках аккаунта")
    print("   -> Должно прийти уведомление о покупке тарифа")
    print()
    print()
    print("=" * 70)
    print(" СПРАВКА")
    print("=" * 70)
    print()
    print("Токен бота выглядит так:")
    print("  1234567890:ABCdefGHIjklMNOpqrsTUVwxyz")
    print()
    print("Chat ID выглядит так:")
    print("  123456789 (положительное число для личного чата)")
    print("  -123456789 (отрицательное число для группового чата)")
    print()
    print("Полная документация:")
    print("  - backend/TELEGRAM_SETUP.md - подробная инструкция")
    print("  - backend/QUICK_TELEGRAM_SETUP.md - краткая инструкция")
    print("  - TELEGRAM_SUMMARY.md - итоговое резюме")
    print()
    print("=" * 70)
    
    # Итоговый статус
    print()
    if token and chat_id and token != "your_telegram_bot_token_here" and chat_id != "your_manager_chat_id_here":
        print("[OK] Настройки выглядят корректно!")
        print()
        print("Следующие шаги:")
        print("1. Найдите вашего бота в Telegram и нажмите START")
        print("2. Запустите: python test_telegram.py")
        print("3. Проверьте, что пришли 4 сообщения")
    else:
        print("[!] Требуется настройка")
        print("    Следуйте инструкциям выше")
    print()

if __name__ == "__main__":
    main()
